sonar.projectKey=manhkien198_fluentry-app
sonar.projectName=fluentry-app
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,mobile/src
sonar.tests=backend/tests,mobile/__tests__

sonar.test.inclusions=**/tests/**/*.py,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mfa-venv/**,**/node_modules/**,**/.expo/**,**/dist/**,**/build/**,**/*.min.js

sonar.python.version=3.11
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=mobile/coverage/lcov.info

sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/tests/**/*.py
